import Head from "next/head";
import styles from "../styles/Home.module.scss";
import HabitCard from "../components/HabitCard";
import Header from "../components/Header";

export default function Faq() {
  return (
    <>
      <Head>
        <title>FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>Hello from FAQ</h2>
      </main>
    </>
  );
}
