import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {
    const habits = [
        {id: 1, name: "Workout", streak: 256},
        {id: 2, name: "Learning French", streak: 123},
        {id: 3, name: "Water", streak: 65}
    ]

    const habitElements = habits.map(h => <div className={styles.habit}
                                               key={h.id}>{`${h.name} : ${h.streak} days streak`}</div>)
    return (
        <>
            <Head>
                <title>My Habits</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <h1>My Habits</h1>
                <div>
                    {habitElements}
                </div>
            </main>
        </>
    )
}
